#!/bin/bash
#
# Short:    Do something when an app is Launched
# Author:   Mark J Swift
# Version:  1.0.7
# Modified: 04-Oct-2016
#
# Called by appwarden as follows:    
#   appwarden-DidLaunch "DidLaunch:Epoch:ApplicationBundleIdentifier:ApplicationName:ApplicationPath:ApplicationProcessIdentifier"

# ---

# Check we have the correct number of parameters
if [ $# -lt 1 ]
then
  exit 0
fi

# -- Script is run as the user with app info as first parameter --

sv_ScriptParam1="${1}"

# Get ApplicationBundleIdentifier e.g. com.apple.TextEdit
# Note, older applications may return "(null)"
sv_ThisAppBundleIdentifier="$(echo ${sv_ScriptParam1} | cut -d":" -f3)"

# Get notification e.g. WillLaunch, DidLaunch or DidTerminate
sv_ThisAppNotificationType="$(echo ${sv_ScriptParam1} | cut -d":" -f1)"

# Get Date/Time Epoch of the notification
iv_ThisAppNotificationEpoch="$(echo ${sv_ScriptParam1} | cut -d":" -f2)"

# Get ApplicationName e.g. TextEdit
sv_ThisAppName="$(echo ${sv_ScriptParam1} | cut -d":" -f4)"

# Get ApplicationPath e.g. /Applications/TextEdit.app
sv_ThisAppFilePath="$(echo ${sv_ScriptParam1} | cut -d":" -f5)"

# Get ApplicationProcessIdentifier - i.e. the process ID
sv_ThisAppProcessID="$(echo ${sv_ScriptParam1} | cut -d":" -f6)"

# ---

# At this point you can do whatever you like - this is just a quick example

say "${sv_ThisAppName} did launch."
